cookbook/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from graphene_django.views import GraphQLView


urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^', include('front.urls', namespace='front')),
]

front/urls.py
from django.conf.urls import url

from front import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^csr/', views.CSRView.as_view(), name='csr'),
]

ingredients/urls.py
from django.conf.urls import url

from ingredients import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^csr', views.CSRView.as_view(), name='csr'),
]

ingredients/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    notes = models.TextField()
    category = models.ForeignKey(
        Category,
        related_name='ingredients',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

ingredients/forms.py
from django import forms

from ingredients.models import Ingredient, Category


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ('name', 'notes', 'category')

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', )

front/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'


class CSRView(TemplateView):
    template_name = 'csr.html'

cookbook/templates/index.html
{% load static %}
<body>
	<div id="app"></div>
	<script src="{% static 'index.js' %}"></script>
    {% csrf_token %}
</body>

front/templates/base.html
<html>
  <head>
    <title>Django Vue SSR Playground</title>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,700" rel="stylesheet">
  </head>
  <body>
    <main>
      {% block content %}{% endblock content %}
    </main>
  </body>
</html>

front/templates/csr.html
{% extends 'base.html' %}

{% load static %}
{% block content%}
	<div id="app"></div>
	<script src="{% static 'index.js' %}"></script>
  {% csrf_token %}
{% endblock content%}

front/templates/index.html
{% extends 'base.html' %}

{% block content%}
	<ul>
    <li>
      <a href="{% url 'front:csr'%}">Client Side Rendering</a>
    </li>
  </ul>
{% endblock content%}

ingredients/templates/index.html
{% extends 'base.html' %}

{% block content%}
	<ul>
    <li>
      <a href="{% url 'ingredients:csr'%}">Client Side Rendering</a>
    </li>
  </ul>
{% endblock content%}